# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(0, 376, 54, 12))
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(50, 310, 171, 58))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 18, 35, 16))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_4.setGeometry(QtCore.QRect(57, 18, 91, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 29, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_6.setGeometry(QtCore.QRect(57, 40, 35, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 370, 199, 25))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 256))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 7, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 1, 1, 3)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 7, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 8, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setTextFormat(QtCore.Qt.PlainText)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 4, 4, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 2, 1, 1, 3)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 7, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 8, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 4, 1, 1, 3)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 5, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 8, 4, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_3.addWidget(self.label_56, 3, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 5, 1, 1, 3)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget)
        self.label_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 4, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget)
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_3.addWidget(self.label_58, 8, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget)
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 7, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget)
        self.label_60.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 6, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 2, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 3, 4, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 6, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 5, 4, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 8, 3, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget)
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 6, 4, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 3, 1, 1, 3)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget)
        self.label_65.setObjectName("label_65")
        self.gridLayout_3.addWidget(self.label_65, 1, 4, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.layoutWidget)
        self.label_66.setObjectName("label_66")
        self.gridLayout_3.addWidget(self.label_66, 6, 2, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget)
        self.label_67.setObjectName("label_67")
        self.gridLayout_3.addWidget(self.label_67, 7, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 1, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 2, 4, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(200, 326, 45, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setGeometry(QtCore.QRect(200, 296, 45, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setEnabled(True)
        self.frame_4.setGeometry(QtCore.QRect(570, 30, 261, 371))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 261, 241))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(0, 10, 261, 91))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.checkBox = QtWidgets.QCheckBox(self.frame_9)
        self.checkBox.setGeometry(QtCore.QRect(10, 0, 141, 16))
        self.checkBox.setObjectName("checkBox")
        self.textEdit = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit.setGeometry(QtCore.QRect(40, 20, 201, 71))
        self.textEdit.setObjectName("textEdit")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(0, 110, 261, 121))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_10)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 0, 121, 16))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_10.setGeometry(QtCore.QRect(20, 21, 211, 16))
        self.radioButton_10.setText("初值       终值       步长")
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_27.setGeometry(QtCore.QRect(66, 20, 35, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_28.setGeometry(QtCore.QRect(132, 20, 35, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_29.setGeometry(QtCore.QRect(200, 20, 35, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame_10)
        self.radioButton_11.setGeometry(QtCore.QRect(20, 50, 13, 13))
        self.radioButton_11.setText("")
        self.radioButton_11.setObjectName("radioButton_11")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_10)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 50, 201, 71))
        self.textEdit_2.setAcceptRichText(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_30.setGeometry(QtCore.QRect(35, 320, 38, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_31.setGeometry(QtCore.QRect(83, 320, 38, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 322, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_32.setGeometry(QtCore.QRect(35, 345, 38, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_33.setGeometry(QtCore.QRect(83, 345, 38, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 250, 100, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 250, 100, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 290, 101, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton_12 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_12.setGeometry(QtCore.QRect(131, 306, 59, 16))
        self.radioButton_12.setChecked(True)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_13.setGeometry(QtCore.QRect(196, 306, 59, 16))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_14.setGeometry(QtCore.QRect(131, 328, 53, 16))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_15.setGeometry(QtCore.QRect(196, 328, 65, 16))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_16.setGeometry(QtCore.QRect(131, 350, 59, 16))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_17.setGeometry(QtCore.QRect(196, 350, 29, 16))
        self.radioButton_17.setObjectName("radioButton_17")
        self.label_3.raise_()
        self.frame_8.raise_()
        self.layoutWidget.raise_()
        self.lineEdit_30.raise_()
        self.lineEdit_31.raise_()
        self.label_6.raise_()
        self.lineEdit_32.raise_()
        self.lineEdit_33.raise_()
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(558, 10, 16, 390))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(50, 366, 155, 36))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_5.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_5.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_5.addWidget(self.radioButton_9)
        self.label_70 = QtWidgets.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(0, 298, 54, 12))
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName("label_70")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 286, 161, 39))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.layoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(320, 30, 241, 334))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_71 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_6.addWidget(self.label_71, 5, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_6.addWidget(self.label_72, 11, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_6.addWidget(self.lineEdit_20, 5, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_6.addWidget(self.lineEdit_22, 7, 1, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_6.addWidget(self.lineEdit_18, 3, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_73.setObjectName("label_73")
        self.gridLayout_6.addWidget(self.label_73, 5, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_6.addWidget(self.lineEdit_16, 1, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_6.addWidget(self.lineEdit_23, 8, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_74.setObjectName("label_74")
        self.gridLayout_6.addWidget(self.label_74, 6, 2, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_75.setObjectName("label_75")
        self.gridLayout_6.addWidget(self.label_75, 9, 2, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_76.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_6.addWidget(self.label_76, 2, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_77.setObjectName("label_77")
        self.gridLayout_6.addWidget(self.label_77, 8, 2, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_6.addWidget(self.lineEdit_19, 4, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_78.setObjectName("label_78")
        self.gridLayout_6.addWidget(self.label_78, 2, 2, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_79.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_79.setObjectName("label_79")
        self.gridLayout_6.addWidget(self.label_79, 6, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_80.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_6.addWidget(self.label_80, 8, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_81.setTextFormat(QtCore.Qt.AutoText)
        self.label_81.setObjectName("label_81")
        self.gridLayout_6.addWidget(self.label_81, 3, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout_6.addWidget(self.label_82, 9, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_6.addWidget(self.lineEdit_15, 0, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_83.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_6.addWidget(self.label_83, 10, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_84.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_6.addWidget(self.label_84, 7, 0, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_6.addWidget(self.lineEdit_26, 11, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_85.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_6.addWidget(self.label_85, 3, 0, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_86.setObjectName("label_86")
        self.gridLayout_6.addWidget(self.label_86, 10, 2, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_87.setObjectName("label_87")
        self.gridLayout_6.addWidget(self.label_87, 11, 2, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_88.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_88.setObjectName("label_88")
        self.gridLayout_6.addWidget(self.label_88, 0, 0, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_6.addWidget(self.lineEdit_24, 9, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_89.setObjectName("label_89")
        self.gridLayout_6.addWidget(self.label_89, 0, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_6.addWidget(self.lineEdit_21, 6, 1, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_90.setObjectName("label_90")
        self.gridLayout_6.addWidget(self.label_90, 7, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_6.addWidget(self.lineEdit_17, 2, 1, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_91.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_91.setObjectName("label_91")
        self.gridLayout_6.addWidget(self.label_91, 4, 0, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_6.addWidget(self.lineEdit_25, 10, 1, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_92.setObjectName("label_92")
        self.gridLayout_6.addWidget(self.label_92, 1, 2, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_93.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_6.addWidget(self.label_93, 1, 0, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_94.setObjectName("label_94")
        self.gridLayout_6.addWidget(self.label_94, 4, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(308, 10, 16, 390))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 10, 115, 16))
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_96 = QtWidgets.QLabel(self.centralwidget)
        self.label_96.setGeometry(QtCore.QRect(0, 330, 54, 12))
        self.label_96.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_96.setObjectName("label_96")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 300, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 54, 12))
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 5, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 5, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "胶体颗粒表面性质与相互作用分析系统  V1.0"))
        self.label_31.setText(_translate("MainWindow", "电解质"))
        self.radioButton_3.setText(_translate("MainWindow", "Li"))
        self.radioButton_4.setText(_translate("MainWindow", "Na      γ="))
        self.radioButton_5.setText(_translate("MainWindow", "K"))
        self.radioButton_6.setText(_translate("MainWindow", "Cs"))
        self.pushButton.setText(_translate("MainWindow", "计算"))
        self.lineEdit_9.setText(_translate("MainWindow", "5"))
        self.lineEdit_2.setText(_translate("MainWindow", "298"))
        self.lineEdit_10.setText(_translate("MainWindow", "-20"))
        self.label_26.setText(_translate("MainWindow", "*10^"))
        self.label_27.setText(_translate("MainWindow", "m^2/g"))
        self.lineEdit_3.setText(_translate("MainWindow", "96485"))
        self.label_28.setText(_translate("MainWindow", "Aeff="))
        self.lineEdit_11.setText(_translate("MainWindow", "1"))
        self.lineEdit_5.setText(_translate("MainWindow", "48"))
        self.label_29.setText(_translate("MainWindow", "x/λ="))
        self.lineEdit_7.setText(_translate("MainWindow", "8.9"))
        self.label_30.setText(_translate("MainWindow", "mol/L"))
        self.label_56.setText(_translate("MainWindow", "CEC="))
        self.lineEdit_6.setText(_translate("MainWindow", "1"))
        self.label_57.setText(_translate("MainWindow", "S="))
        self.label_58.setText(_translate("MainWindow", "c="))
        self.label_59.setText(_translate("MainWindow", "J"))
        self.lineEdit.setText(_translate("MainWindow", "8.314"))
        self.label_60.setText(_translate("MainWindow", "ε="))
        self.label_61.setText(_translate("MainWindow", "F="))
        self.label_62.setText(_translate("MainWindow", "cmol/kg"))
        self.lineEdit_8.setText(_translate("MainWindow", "-10"))
        self.label_8.setText(_translate("MainWindow", "J/(K mol)"))
        self.label_63.setText(_translate("MainWindow", "nm"))
        self.lineEdit_12.setText(_translate("MainWindow", "-4"))
        self.label_64.setText(_translate("MainWindow", "C^2/(J dm)"))
        self.lineEdit_4.setText(_translate("MainWindow", "16"))
        self.label_65.setText(_translate("MainWindow", "K"))
        self.label_66.setText(_translate("MainWindow", "*10^"))
        self.label_67.setText(_translate("MainWindow", "*10^"))
        self.label_4.setText(_translate("MainWindow", "R="))
        self.label_68.setText(_translate("MainWindow", "T="))
        self.label_69.setText(_translate("MainWindow", "C/mol"))
        self.lineEdit_14.setText(_translate("MainWindow", "1"))
        self.lineEdit_13.setText(_translate("MainWindow", "-0.3"))
        self.checkBox.setText(_translate("MainWindow", "多浓度"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.0001,0.001,0.01,0.1,1</p></body></html>"))
        self.checkBox_2.setText(_translate("MainWindow", "多距离"))
        self.lineEdit_27.setText(_translate("MainWindow", "2"))
        self.lineEdit_28.setText(_translate("MainWindow", "10"))
        self.lineEdit_29.setText(_translate("MainWindow", "2"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1,2,3,4,5,6,7,8,9,10</p></body></html>"))
        self.lineEdit_30.setText(_translate("MainWindow", "0.2"))
        self.lineEdit_31.setText(_translate("MainWindow", "10"))
        self.lineEdit_32.setText(_translate("MainWindow", "0"))
        self.lineEdit_33.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "X轴:       -"))
        self.label_6.setText(_translate("MainWindow", "Y轴:       -"))
        self.pushButton_4.setText(_translate("MainWindow", "计算"))
        self.pushButton_5.setText(_translate("MainWindow", "打开excel"))
        self.pushButton_6.setText(_translate("MainWindow", "绘图"))
        self.radioButton_12.setText(_translate("MainWindow", "p(vdW)"))
        self.radioButton_13.setText(_translate("MainWindow", "P(edl)"))
        self.radioButton_14.setText(_translate("MainWindow", "P(hy)"))
        self.radioButton_15.setText(_translate("MainWindow", "P(dlvo)"))
        self.radioButton_16.setText(_translate("MainWindow", "P(net)"))
        self.radioButton_17.setText(_translate("MainWindow", "E"))
        self.radioButton_7.setText(_translate("MainWindow", "1:1"))
        self.radioButton_8.setText(_translate("MainWindow", "1:2"))
        self.radioButton_9.setText(_translate("MainWindow", "2:1"))
        self.label_70.setText(_translate("MainWindow", "计算模式"))
        self.radioButton.setText(_translate("MainWindow", "方程"))
        self.radioButton_2.setText(_translate("MainWindow", "指定:φ(0)="))
        self.label_71.setText(_translate("MainWindow", "1/κ="))
        self.label_72.setText(_translate("MainWindow", "E="))
        self.label_73.setText(_translate("MainWindow", "nm"))
        self.label_74.setText(_translate("MainWindow", "atm"))
        self.label_75.setText(_translate("MainWindow", "atm"))
        self.label_76.setText(_translate("MainWindow", "φ(x)="))
        self.label_77.setText(_translate("MainWindow", "atm"))
        self.label_78.setText(_translate("MainWindow", "V"))
        self.label_79.setText(_translate("MainWindow", "P(edl)="))
        self.label_80.setText(_translate("MainWindow", "P(hy)="))
        self.label_81.setText(_translate("MainWindow", "C/m^2"))
        self.label_82.setText(_translate("MainWindow", "P(DLVO)="))
        self.label_83.setText(_translate("MainWindow", "P(net)="))
        self.label_84.setText(_translate("MainWindow", "P(vdW)="))
        self.label_85.setText(_translate("MainWindow", "σ(0)="))
        self.label_86.setText(_translate("MainWindow", "atm"))
        self.label_87.setText(_translate("MainWindow", "V/m"))
        self.label_88.setText(_translate("MainWindow", "φ(0)="))
        self.label_89.setText(_translate("MainWindow", "V"))
        self.label_90.setText(_translate("MainWindow", "atm"))
        self.label_91.setText(_translate("MainWindow", "κ="))
        self.label_92.setText(_translate("MainWindow", "V"))
        self.label_93.setText(_translate("MainWindow", "φ(λ/2)="))
        self.label_94.setText(_translate("MainWindow", "1/m"))
        self.label_7.setText(_translate("MainWindow", "多浓度/多距离"))
        self.label_96.setText(_translate("MainWindow", "离子类型"))
        self.label_5.setText(_translate("MainWindow", "V"))
        self.label_2.setText(_translate("MainWindow", "单浓度单距离"))
        self.label.setText(_translate("MainWindow", "参数输入"))
        self.pushButton_2.setText(_translate("MainWindow", "导入参数"))
        self.pushButton_3.setText(_translate("MainWindow", "导出参数"))
